### ISSUE TITLE
App only crashes

### ISSUE THREAD

**Issue by Rbagman** [corphish/NightLight#29]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.corphish.nightlight.generic/com.corphish.nightlight.StartActivity}: android.content.res.Resources$NotFoundException: File res/drawable/splash.xml from drawable resource ID #0x7f080083
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/splash.xml from drawable resource ID #0x7f080083
	at android.content.res.Resources.loadDrawable(Resources.java:3422)
	at android.content.res.Resources.getDrawable(Resources.java:1909)
	at android.content.res.XResources.getDrawable(XResources.java:521)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:465)
	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
	at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
	at androidx.appcompat.app.AppCompatDelegateImpl.<init>(AppCompatDelegateImpl.java:258)
	at androidx.appcompat.app.AppCompatDelegate.create(AppCompatDelegate.java:182)
	at androidx.appcompat.app.AppCompatActivity.getDelegate(AppCompatActivity.java:520)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
	at com.corphish.nightlight.StartActivity.onCreate(StartActivity.kt:33)
	at android.app.Activity.performCreate(Activity.java:5451)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
	... 12 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_lightbulb_splash_vector.xml from drawable resource ID #0x7f08006b
	at android.content.res.Resources.loadDrawable(Resources.java:3422)
	at android.content.res.Resources.getDrawable(Resources.java:1909)
	at android.content.res.XResources.getDrawable(XResources.java:521)
	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:159)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:990)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
	at android.content.res.Resources.loadDrawable(Resources.java:3418)
	... 25 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
	at android.content.res.Resources.loadDrawable(Resources.java:3418)
	... 31 more

**Comment by corphish** [comment]
Usually re-installing the app fixes this issue.
